services:
  gethomepage-tool-box:
    container_name: Gethomepage-Tool-Box
    image: ghcr.io/10mfox/gethomepage-tool-box:main   
    ports:
      - "5054:5000" # Map host port 5054 to container port 5000
    environment:
      - TAUTULLI_URL=http://0.0.0.0:8181
      - TAUTULLI_API_KEY=your-key
    restart: always