name: 🐛 Bug Report
description: Create a report to help improve the application.
title: "[BUG] - A brief description of the bug"
labels: ["bug"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Please provide the exact steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: dropdown
    id: data-source
    attributes:
      label: Environment - Data Source
      description: Which data source is related to this bug?
      options:
        - Tautulli
        - Jellystat
        - Audiobookshelf
        - Other (Please specify below)
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please paste any relevant logs from the `media-manager` container by running `docker logs media-manager`.
      render: shell
